name: background_location_tracker_example
description: Demonstrates how to use the background_location_tracker plugin.
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  background_location_tracker: ^1.5.0
  connectivity_plus: ^6.1.3
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  http: ^1.3.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  image_path: "assets/playstore.png"  
  adaptive_icon_background: "#FFFFFF" 